version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "generateMeme"
        Alias: "generateMemeAlias"
        CurrentVersion: "1"
        TargetVersion: "1"
